name: prometheus-operator
namespace: giantswarm
serviceType: managed
crdApiGroup: monitoring.coreos.com

userID: 65534
groupID: 65534

image:
  repository: quay.io/coreos/prometheus-operator
  tag: v0.30.0

prometheusConfigReloaderImage:
  repository: quay.io/coreos/prometheus-config-reloader
  tag: v0.30.0

configmapReloadImage:
  repository: quay.io/coreos/configmap-reload
  tag: v0.0.1
