apiVersion: v1
appVersion: 0.31.1
description: A Helm Chart for Prometheus Operator.
engine: gotpl
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
name: prometheus-operator-app-chart
sources:
- https://github.com/giantswarm/prometheus-operator-app
version: [[ .Version ]]
